### ISSUE TITLE
error whil fetching input github:invoke-ai

### ISSUE THREAD

**Issue by DavHau** [nixified-ai/flake#17]
command:
```command
nix flake show github:nixified-ai/flake --show-trace
```
output:
```command
...
… while fetching the input 'github:invoke-ai/InvokeAI/650f4bb58ceca458bff1410f35cd6d6caad399c6'

       error: failed to extract archive (truncated gzip input)
```

**Comment by MatthewCroughan** [comment]
This is new, how can this be anything but an error with the file github is serving?

**Comment by DavHau** [comment]
Or maybe a caching issue of nix. I remember my network breaking down whole fetching the input the first time. I'll investigate a bit when I find time.

**Comment by MatthewCroughan** [comment]
@max-privatevoid that would mean not using flake inputs. I'm not up for that.

**Comment by DavHau** [comment]
I think flake inputs are fine. Was just arare bug happening on my machine. It actually built fine later on when I tried again after a GC
Thanks for the cool project BTW.
