### ISSUE TITLE
Feature request: Support for text-generation-webui

### ISSUE THREAD

**Issue by LowYieldFire** [nixified-ai/flake#25]
[Text generation webui](https://github.com/oobabooga/text-generation-webui) has support for more models than KoboldAI, especially the ability to use 4bit models is a major improvement. It would be great if we had a simple process for setting it up using Nix.

**Comment by ChrisCochrun** [comment]
I too think this would be an awesome addition. I've been trying to get it working on my own, and cannot thus far.

**Comment by happysalada** [comment]
I opened an issue in stable-diffusion-webui (which is very similar ) for them use poetry, to make it easier to oackage nix. They responded with the fact that you need flags for different gpu which are not supported by poetry.
Not being able to rely on poetry might make this task harder.

**Comment by MatthewCroughan** [comment]
@happysalada I have played around with the idea of simply upstreaming our overlays to Nixpkgs, which provides massive value to Nixpkgs. In practice, the waiting time for upstreaming to Nixpkgs would be negligible compared to development time here, and results in a cleaner and simpler nix codebase for us. This is with or without poetry2nix.

**Comment by LowYieldFire** [comment]
Quite a few people seem to be ending up on this issue so let me share what I've been using recently.

While text-generation-webui is currently not easy to run, the library behind it, [llama.cpp](https://github.com/ggerganov/llama.cpp), is. You can easily run it if you have flake support enabled by running the following commands:

```bash
nix shell github:ggerganov/llama.cpp
llama -ins -t n_threads -m path/to/model.bin --multiline-input --color -c 512
```

Where `n_threads` should be replaced with the number of threads you want to use, and `path/to/model.bin` with the path to the model. `-c 512` sets the max context length, in this case 512 tokens (max 4096 i believe), longer context length slows the model considerably. 

This will provide you with an easy to use TUI where you can chat with the model. With this setup I can run 5 bit quantized models with `30B` parameters on CPU only at a rate of 700 ms/token, and as little as 1.7gb ram use.

**Comment by max-privatevoid** [comment]
Resolved via https://github.com/nixified-ai/flake/releases/tag/2
