### ISSUE TITLE
Permission denied for --web without specifying --outdir

### ISSUE THREAD

**Issue by gubbu** [nixified-ai/flake#28]
Thanks for the flake! The console interface for invokeai works, no errors found of any kind.

However when I want to run the web-UI:
`nix run github:nixified-ai/flake#invokeai-nvidia --extra-experimental-features flakes --extra-experimental-features nix-command -- --web`

I also get a permission denied error (Similar to https://github.com/nixified-ai/flake/issues/6 ?): 
PermissionError: [Errno 13] Permission denied: '../outputs'

I get a permission denied error in the invoke_ai_web_server.py for ../outputs :

![image](https://user-images.githubusercontent.com/38842604/233746527-7966521f-c88a-49b8-91d3-15e403670842.png)

I guess it is meant to be ~/invokeai/outputs , and it wants to crate new folders there with mkdirs in line 282 invoke_ai_web_server.py? 

Now, only after specifying the outdir argument
`--outdir ~/Pictures/invokeai_output`

The web UI runs:
`nix run github:nixified-ai/flake#invokeai-nvidia --extra-experimental-features flakes --extra-experimental-features nix-command -- --web --outdir ~/Pictures/invokeai_output`

**Intended default behavior:** This should also run without specifying --outdir.

**Comment by MatthewCroughan** [comment]
This is the behavior of the upstream program invokeai. The way they handle state is very problematic, and poorly designed. I do not want to control that. The best way to run invokeai is by using the NixOS Modules we provide, `services.invokeai.enable = true`.
