### ISSUE TITLE
Is it possible to access the CLI for invoked-ai via this flake?

### ISSUE THREAD

**Issue by qwbarch** [nixified-ai/flake#39]
When running ``nix run .#invokeai-nvidia``, is it possible to somehow access the CLI?
By the way, thanks for packaging this into a nix flake! This is exactly what I needed

**Comment by MatthewCroughan** [comment]
@qwbarch yeah, that's what passing `--` alone does to the nix command line. So there's two ways:

1. `nix run .#invokeai-nvidia -- --the --real --stuff --you --want --to --pass --web`
2. 
    ```
    nix shell .#invokeai-nvidia
    invokeai --the --real --stuff --you --want --to --pass --web
    ```

**Comment by qwbarch** [comment]
Thanks a lot!
