### ISSUE TITLE
please add support for text-generation-webui

### ISSUE THREAD

**Issue by DarkReaperBoy** [nixified-ai/flake#45]
this is the repo
https://github.com/oobabooga/text-generation-webui

**Comment by MatthewCroughan** [comment]
This is half-complete via https://github.com/nixified-ai/flake/pull/29, but please consider sponsoring the project or contributing, as I don't have time to complete it. This is one of our funding goals.

**Comment by pbsds** [comment]
This too? https://github.com/go-skynet/LocalAI

**Comment by dmadisetti** [comment]
What all needs to be done on the branch? Not clear from the PR

Interface and model inference seem to work for me (nvidia)

**Comment by dmadisetti** [comment]
Working with the most recent version: https://github.com/AnotherGroupChat/ai-flake/tree/dm/wip-text-generation-webui

I think patch hacks are going to have to be an upstream change

Tracking a pkgs solution here: https://github.com/NixOS/nixpkgs/issues/231810

**Comment by max-privatevoid** [comment]
Resolved via https://github.com/nixified-ai/flake/releases/tag/2

**Comment by shpinog** [comment]
> Resolved via https://github.com/nixified-ai/flake/releases/tag/2

No longer relevant, abandoned. Are there any workarounds?
