### ISSUE TITLE
Permission Denied on Fresh Install (InvokeAI)

### ISSUE THREAD

**Issue by garaiza-93** [nixified-ai/flake#6]
Hello, and thanks for the neat flake! It really helps streamline the installation process that Invoke AI requires.
However, it seems that I am running into a permissions issue, and I am unsure if it's relevant to this repository but I am making this issue just in case it is.
What tends to happen is:
1. `nix run github:nixified-ai/flake/mc/update-invokeai#invokeai-nvidia -- --web` (to use the latest version of Invoke AI)
2. `models.yaml` not found, so `invokeai-configure` runs.
3. After configuration, models are downloaded
4. InvokeAI creates `configs/` without write permissions
5. InvokeAI attempts to create `models.yaml` but doesn't have write permissions
6. `PermissionsError`
Here is the output I get:
![image](https://user-images.githubusercontent.com/57430880/222572544-37cde659-73d6-4f1e-8e62-851ef851f938.png)
![image](https://user-images.githubusercontent.com/57430880/222572577-97d73ba0-8fc7-4e17-8f31-aca5a5d7b5c3.png)

If you need more info let me know. Thanks!

**Comment by MatthewCroughan** [comment]
Yeah this was in development before we announce the project in a big way, the latest version of InvokeAI is more sensible and @max-privatevoid is working on a nixosModule that allows you to declarative specify the models to download, so this is going to be fixed shortly.

**Comment by garaiza-93** [comment]
Awesome, thanks! I'll close this issue for now. Max suggested that I use a workaround to change the permissions for `config/`. However, without knowing when Invoke AI creates that directory without write permissions, I just spammed it until I could finally get InvokeAI working. Will try to track it down.

Workaround: `chmod +w -R`

**Comment by MatthewCroughan** [comment]
I've been working on this in a branch and I've found that line 666 (not a joke) of `ldm/invoke/config/invokeai_configure.py` is causing it, and this is the fix. This will be merged soon.

```sh
    substituteInPlace ./ldm/invoke/config/invokeai_configure.py --replace \
      "shutil.copytree(configs_src, configs_dest, dirs_exist_ok=True)" \
      "subprocess.call('cp -r --no-preserve=mode {configs_src} {configs_dest}'.format(configs_src=configs_src, configs_dest=configs_dest), shell=True)"
```
