### ISSUE TITLE
can there be a new target "vulkan" be added?

### ISSUE THREAD

**Issue by 6543** [nixified-ai/flake#77]
I have an intel arc 750 and would like to use the ai via vulkan api.
PyTourch should support it but you have to compile it with a feature flag manually enabled.

projects like **realesrgan-ncnn-vulkan** work nice so it should be doable?

**Comment by MatthewCroughan** [comment]
This has nothing to do with nixified-ai, you need to ask the upstream projects, nixpkgs, or override the derivation(s) if you want that.
