### ISSUE TITLE
Python3.11 doesnt ever finish building

### ISSUE THREAD

**Issue by JonnyDeates** [nixified-ai/flake#99]
It gets hung up on pulling the package for python3.11-torch-2.0.1.

![image](https://github.com/user-attachments/assets/9726a0ac-987d-42d7-8bb5-bb6d3e075228)

**Comment by JonnyDeates** [comment]
I cloned the repository, and then ran the command nix run .#invokeai-amd,
I have a nix os machine using home manager, and have an AMD Ryzen™ 9 7900X cpu, and a AMD Radeon RX 7900 XTX gpu.

**Comment by JonnyDeates** [comment]
I also use zaneyos, and a snapshot of the newest home manager / nixpkgs builds.

**Comment by MatthewCroughan** [comment]
You likely don't have enough resources on the computer to build Torch from source.

**Comment by MatthewCroughan** [comment]
You can verify this by not using Nix, and by compiling torch from source without Nix, and seeing if it takes the same amount of time. You should use the cache.
